import fs from 'node:fs';
import path from 'node:path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// A guide section appears once its folder exists under docs/.
const section = (dirName: string, label: string) =>
  fs.existsSync(path.join(__dirname, 'docs', dirName))
    ? [{type: 'category' as const, label, collapsed: false, items: [{type: 'autogenerated' as const, dirName}]}]
    : [];

// The API reference sidebars are generated by `npm run docs:gen`.
const apiSection = (api: string, label: string) => {
  const file = path.join(__dirname, 'docs', 'api', api, 'sidebar.ts');
  if (!fs.existsSync(file)) return [];
  // The generated file's default export is the item array itself.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const generated = require(file).default;
  return [{type: 'category' as const, label, collapsed: false, items: generated}];
};

const sidebars: SidebarsConfig = {
  guide: [
    'intro',
    ...section('use-case', 'Use case'),
    ...section('standards', 'Standards'),
    ...section('contracts', 'Contracts'),
    ...section('overlays', 'Overlays'),
    ...section('workflows', 'Workflows'),
    ...section('architecture', 'Architecture'),
    ...section('maintain', 'Maintain'),
  ],
  api: [
    ...apiSection('common', 'Common API'),
    ...apiSection('banking', 'Banking API'),
    ...apiSection('consent', 'Consent API'),
  ],
};

export default sidebars;
